extends RefCounted

func run(support) -> void:
	var store = load("res://client/domain/annotation_store.gd").new()
	var records := []
	for frame in range(3):
		records.append({"schema_version": 1, "source": "clip", "frame": frame, "time_s": float(frame), "regions": [{"id": "r", "kind": "instrument", "class": "tool", "box": [frame, 0, 10, 10]}]})
	support.expect_equal(store.load_model_records(records), PackedStringArray(), "fixture loads")
	support.expect(store.has_method("is_verified"), "store exposes content-bound verification")
	if not store.has_method("is_verified"):
		return
	var history = load("res://client/domain/command_history.gd").new()
	var review_script = load("res://client/domain/commands/review_frames_command.gd")
	support.expect_equal(history.execute(review_script.new([1, 2], true), store), PackedStringArray(), "range verification succeeds")
	support.expect(store.is_verified(1) and store.is_verified(2), "range accepted")
	support.expect(history.undo(store), "review undo succeeds")
	support.expect(not store.is_verified(1), "review undo removes acceptance")
	support.expect_equal(history.redo(store), PackedStringArray(), "review redo")
	var propagation = load("res://client/domain/commands/propagate_range_command.gd").new(0, 0, 2, "overwrite", {"metric": "test", "threshold": 0.02, "keyframe": 999})
	support.expect_equal(history.execute(propagation, store), PackedStringArray(), "propagate commits")
	support.expect(not store.is_verified(1), "changed content invalidates acceptance")
	support.expect_equal(store.snapshot_batch_operations()[0].keyframe, 0, "metadata cannot replace structural marker")
	support.expect(history.undo(store), "propagation undo")
	support.expect(store.is_verified(1) and store.is_verified(2), "restored content restores acceptance")
	support.expect(store.snapshot_batch_operations().is_empty(), "undo removes marker")
	var duplicate_record: Dictionary = store.get_corrected_record(1)
	duplicate_record.regions.append(duplicate_record.regions[0].duplicate(true))
	support.expect(not store.replace_corrected_record(1, duplicate_record).is_empty(), "duplicate region IDs rejected")
	var prior_records: Array = store.snapshot_corrected()
	support.expect(not store.replace_corrected_records({1: store.get_corrected_record(1)}, {"type": "bad"}).is_empty(), "invalid propagation marker rejected")
	support.expect_equal(store.snapshot_corrected(), prior_records, "invalid marker atomic")
	var root := "/tmp/annotool-batch-%d" % Time.get_ticks_usec()
	DirAccess.make_dir_recursive_absolute(root)
	var label = load("res://client/workspace/media_label_store.gd").new()
	var entries := [{"frame_id": 0, "time_s": 0.0}, {"frame_id": 1, "time_s": 1.0}, {"frame_id": 2, "time_s": 2.0}]
	var media := {"media_id": "clip", "media_type": "image_sequence", "relative_path": "videos/clip", "source_sha256": null}
	support.expect_equal(label.prepare(root, media, entries, records), PackedStringArray(), "label prepares")
	support.expect_equal(label.flush(), PackedStringArray(), "initial save")
	support.expect_equal(label.replace_workflow_state(store.snapshot_review_state(), store.snapshot_batch_operations()), PackedStringArray(), "accept workflow metadata")
	support.expect(label.has_pending_changes(), "metadata-only is dirty")
	support.expect_equal(label.flush(), PackedStringArray(), "metadata saves")
	var reopened = load("res://client/workspace/media_label_store.gd").new()
	support.expect_equal(reopened.prepare(root, media, entries), PackedStringArray(), "V2 reopens")
	var restored = load("res://client/domain/annotation_store.gd").new()
	restored.load_model_records(reopened.all_display_records())
	var workflow: Dictionary = reopened.workflow_state()
	support.expect_equal(restored.load_workflow_state(workflow.review_state, workflow.batch_operations), PackedStringArray(), "load workflow")
	support.expect(restored.is_verified(1), "acceptance survives JSON numeric roundtrip")
	var invalid: Dictionary = workflow.review_state.duplicate(true)
	invalid["999"] = {"accepted_digest": "a".repeat(64)}
	support.expect(not restored.load_workflow_state(invalid, []).is_empty(), "unknown reviews rejected atomically")
	support.expect(restored.is_verified(1), "invalid workflow leaves state intact")
	support.expect_equal(history.redo(store), PackedStringArray(), "propagation redo for persisted marker")
	for frame in [1, 2]:
		label.replace_record(frame, store.get_corrected_record(frame))
	label.replace_workflow_state(store.snapshot_review_state(), store.snapshot_batch_operations())
	support.expect_equal(label.flush(), PackedStringArray(), "save propagation with retained acceptance")
	support.expect_equal(reopened.prepare(root, media, entries), PackedStringArray(), "reopen batch marker")
	support.expect_equal(reopened.workflow_state().batch_operations.size(), 1, "batch marker roundtrips")
	restored.load_model_records(reopened.all_display_records())
	workflow = reopened.workflow_state()
	restored.load_workflow_state(workflow.review_state, workflow.batch_operations)
	support.expect(not restored.is_verified(1), "stale acceptance remains unverified after reload")
	support.expect(not restored.snapshot_review_state().is_empty(), "reload retains acceptance digest for restored content")
	var count_before: int = history.get_undo_count()
	var no_change = load("res://client/domain/commands/propagate_range_command.gd").new(0, 0, 2, "overwrite")
	support.expect(not history.execute(no_change, store).is_empty(), "no-op propagation refused")
	support.expect_equal(history.get_undo_count(), count_before, "no-op adds no history")
	support.expect_equal(store.snapshot_batch_operations().size(), 1, "no-op adds no marker")
	# A metadata-only save must block navigation and survive retry.
	var failure_root := root + "-failure"
	DirAccess.make_dir_recursive_absolute(failure_root)
	var blocker := FileAccess.open(failure_root.path_join("label"), FileAccess.WRITE)
	blocker.store_string("occupied")
	blocker.close()
	var pending = load("res://client/workspace/media_label_store.gd").new()
	support.expect_equal(pending.prepare(failure_root, media, entries), PackedStringArray(), "prepare despite blocked destination")
	var empty_store = load("res://client/domain/annotation_store.gd").new()
	empty_store.load_model_records(pending.all_display_records())
	var session = load("res://client/workspace/workspace_session.gd").new()
	session.bind(empty_store, pending, Callable(), Callable())
	support.expect_equal(review_script.new([0], true).apply(empty_store), PackedStringArray(), "metadata signal accepted")
	support.expect(pending.has_pending_changes() and pending.dirty_frame_ids().is_empty(), "session copies metadata without record edit")
	support.expect(not session.flush_before_context_change().is_empty(), "metadata failure surfaced")
	support.expect(not session.can_replace_context(), "save failure blocks context replacement")
	DirAccess.rename_absolute(failure_root.path_join("label"), failure_root.path_join("label.blocker"))
	support.expect_equal(session.retry_unsaved(), PackedStringArray(), "metadata retry succeeds")
	support.expect(session.can_replace_context(), "successful retry releases context")
	session.unbind()
	session.free()
	# V1 has no workflow; invalid versions are refused, not silently downgraded.
	var native_path: String = label.label_path()
	var payload: Dictionary = JSON.parse_string(FileAccess.get_file_as_string(native_path))
	payload.schema_version = 1
	payload.erase("review_state")
	payload.erase("batch_operations")
	_write_payload(native_path, payload)
	support.expect_equal(reopened.prepare(root, media, entries), PackedStringArray(), "V1 loads")
	support.expect_equal(reopened.workflow_state(), {"review_state": {}, "batch_operations": []}, "V1 initializes no workflow")
	payload.schema_version = 2.5
	_write_payload(native_path, payload)
	support.expect(not reopened.prepare(root, media, entries).is_empty(), "fractional schema version rejected")

func _write_payload(path: String, payload: Dictionary) -> void:
	var file := FileAccess.open(path, FileAccess.WRITE)
	file.store_string(JSON.stringify(payload))
	file.close()
