extends SceneTree

const FRONTEND_STRUCTURE_TEST = preload("res://tests/godot/test_frontend_structure.gd")
const DATASET_EXPLORER_TEST = preload("res://tests/godot/test_dataset_explorer.gd")
const TOOL_PANEL_TEST = preload("res://tests/godot/test_tool_panel.gd")
const MODEL_OUTPUT_VALIDATOR_TEST = preload("res://tests/godot/test_model_output_validator.gd")
const ANNOTATION_STORE_TEST = preload("res://tests/godot/test_annotation_store.gd")
const MODEL_OUTPUT_IMMUTABILITY_TEST = preload("res://tests/godot/test_model_output_immutability.gd")
const PLUGIN_REGISTRY_TEST = preload("res://tests/godot/test_plugin_registry.gd")
const SOURCE_PLUGIN_TEST = preload("res://tests/godot/test_source_plugin.gd")
const SINGLE_IMAGE_SOURCE_TEST = preload("res://tests/godot/test_single_image_source.gd")
const FEEDBACK_PLUGIN_TEST = preload("res://tests/godot/test_feedback_plugin.gd")
const VIEWPORT_TRANSFORM_TEST = preload("res://tests/godot/test_viewport_transform.gd")
const EDIT_SESSION_TEST = preload("res://tests/godot/test_edit_session.gd")
const EDIT_OVERLAY_TEST = preload("res://tests/godot/test_edit_overlay.gd")
const MASK_REGION_OPS_TEST = preload("res://tests/godot/test_mask_region_ops.gd")
const REGION_GEOMETRY_TEST = preload("res://tests/godot/test_region_geometry.gd")
const CLASS_COLOR_RESOLVER_TEST = preload("res://tests/godot/test_class_color_resolver.gd")
const PROJECT_CLASS_CATALOG_TEST = preload("res://tests/godot/test_project_class_catalog.gd")
const ANNOTATION_SIDEBAR_TEST = preload("res://tests/godot/test_annotation_sidebar.gd")
const CLASS_ASSIGNMENT_DIALOG_TEST = preload("res://tests/godot/test_class_assignment_dialog.gd")
const RENDERER_TEST = preload("res://tests/godot/test_renderer.gd")
const ANNOTATION_VIEWPORT_TEST = preload("res://tests/godot/test_annotation_viewport.gd")
const EDIT_COMMANDS_TEST = preload("res://tests/godot/test_edit_commands.gd")
const REGION_EDIT_COMMANDS_TEST = preload("res://tests/godot/test_region_edit_commands.gd")
const KEYBOARD_EDITING_TEST = preload("res://tests/godot/test_keyboard_editing.gd")
const REAL_EDIT_INTEGRATION_TEST = preload("res://tests/godot/test_edit_integration.gd")
const RANGE_PROPAGATION_TEST = preload("res://tests/godot/test_range_propagation.gd")
const PLAYBACK_TEST = preload("res://tests/godot/test_playback.gd")
const PLAYBACK_CONTROLLER_TEST = preload("res://tests/godot/test_playback_controller.gd")
const PLAYBACK_FPS_METER_TEST = preload("res://tests/godot/test_playback_fps_meter.gd")
const PLAYBACK_SPEED_CONTROL_TEST = preload("res://tests/godot/test_playback_speed_control.gd")
const VIDEO_IMPORT_CONTROLLER_TEST = preload("res://tests/godot/test_video_import_controller.gd")
const TIMELINE_TEST = preload("res://tests/godot/test_timeline.gd")
const MAIN_BOUNDARIES_TEST = preload("res://tests/godot/test_main_boundaries.gd")
const WORKSPACE_CATALOG_TEST = preload("res://tests/godot/test_workspace_catalog.gd")
const WORKSPACE_SEQUENCE_SOURCE_TEST = preload("res://tests/godot/test_workspace_sequence_source.gd")
const MEDIA_LABEL_STORE_TEST = preload("res://tests/godot/test_media_label_store.gd")
const CHOLECT50_LABEL_ADAPTER_TEST = preload("res://tests/godot/test_cholect50_label_adapter.gd")
const WORKSPACE_SESSION_TEST = preload("res://tests/godot/test_workspace_session.gd")
const WORKSPACE_MEDIA_CONTROLLER_TEST = preload("res://tests/godot/test_workspace_media_controller.gd")
const WORKSPACE_INTEGRATION_TEST = preload("res://tests/godot/test_workspace_integration.gd")
const TEST_SUPPORT = preload("res://tests/godot/test_support.gd")


func _init() -> void:
	call_deferred("_run_tests")


func _run_tests() -> void:
	var support = TEST_SUPPORT.new()
	await TOOL_PANEL_TEST.new().run(support, self)
	await DATASET_EXPLORER_TEST.new().run(support, self)
	await FRONTEND_STRUCTURE_TEST.new().run(support, self)
	MODEL_OUTPUT_VALIDATOR_TEST.run(support)
	ANNOTATION_STORE_TEST.run(support)
	MODEL_OUTPUT_IMMUTABILITY_TEST.run(support)
	PLUGIN_REGISTRY_TEST.run(support)
	SOURCE_PLUGIN_TEST.run(support)
	SINGLE_IMAGE_SOURCE_TEST.new().run(support)
	FEEDBACK_PLUGIN_TEST.new().run(support)
	VIEWPORT_TRANSFORM_TEST.run(support)
	EDIT_SESSION_TEST.run(support)
	await EDIT_OVERLAY_TEST.new().run(support, self)
	MASK_REGION_OPS_TEST.run(support)
	REGION_GEOMETRY_TEST.run(support)
	CLASS_COLOR_RESOLVER_TEST.run(support)
	PROJECT_CLASS_CATALOG_TEST.run(support)
	await ANNOTATION_SIDEBAR_TEST.new().run(support, self)
	await CLASS_ASSIGNMENT_DIALOG_TEST.new().run(support, self)
	RENDERER_TEST.run(support)
	await ANNOTATION_VIEWPORT_TEST.new().run(support, self)
	EDIT_COMMANDS_TEST.run(support)
	REGION_EDIT_COMMANDS_TEST.run(support)
	KEYBOARD_EDITING_TEST.run(support)
	RANGE_PROPAGATION_TEST.run(support)
	PLAYBACK_CONTROLLER_TEST.run(support)
	PLAYBACK_FPS_METER_TEST.run(support)
	await PLAYBACK_SPEED_CONTROL_TEST.new().run(support, self)
	await VIDEO_IMPORT_CONTROLLER_TEST.new().run(support, self)
	# Includes the mounted main.tscn matrix driven only through runtime UI input.
	await REAL_EDIT_INTEGRATION_TEST.new().run(support, self)
	await PLAYBACK_TEST.new().run(support, self)
	await TIMELINE_TEST.new().run(support, self)
	await MAIN_BOUNDARIES_TEST.new().run(support, self)
	WORKSPACE_CATALOG_TEST.new().run(support)
	WORKSPACE_SEQUENCE_SOURCE_TEST.new().run(support)
	MEDIA_LABEL_STORE_TEST.new().run(support)
	CHOLECT50_LABEL_ADAPTER_TEST.new().run(support)
	await WORKSPACE_SESSION_TEST.new().run(support, self)
	await WORKSPACE_MEDIA_CONTROLLER_TEST.new().run(support, self)
	await WORKSPACE_INTEGRATION_TEST.new().run(support, self)
	if support.failures.is_empty():
		print("PASS: complete Godot test suite")
		quit(0)
		return
	push_error("FAIL: Godot test suite\n%s" % support.failure_report())
	quit(1)
